#!/usr/bin/env bash
# installing nginx on my server and serving an HTML file afterwards

apt-get update -y
apy-get install nginx -y
sudo ufw allow "nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx restart
