#!/usr/bin/env bash
# installing nginx on my server and serving an HTML file afterwards

apt-get update -y
apt-get install nginx -y
sudo ufw allow "nginx HTTP"
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
